### ISSUE TITLE
[0.15] monitor needs new @Colyseus/core import 

### ISSUE THREAD

**Issue by arpu** [colyseus/colyseus.js#118]
Server example from 0.15 branch does not start 

```
- /home/arpu/Work/projects/colyseus/packages/example/node_modules/@colyseus/monitor/build/api.js
- /home/arpu/Work/projects/colyseus/packages/example/node_modules/@colyseus/monitor/build/index.js
- /home/arpu/Work/projects/colyseus/packages/example/src/Server.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/arpu/Work/projects/colyseus/packages/example/node_modules/@colyseus/monitor/build/api.js:16:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/arpu/Work/projects/colyseus/packages/example/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.nodeDevHook [as .js] (/home/arpu/Work/projects/colyseus/packages/example/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
[ERROR] 18:56:43 Error: Cannot find module 'colyseus'
```

**Comment by arpu** [comment]
wups looks like this is in the wrong project closing
