### ISSUE TITLE
Cocos Creator Unavailable in colyseus.js 0.15

### ISSUE THREAD

**Issue by long51xy** [colyseus/colyseus.js#134]
Cocos Creator 3.81 
![image](https://github.com/colyseus/colyseus.js/assets/5525950/43545dd8-8853-4f9d-89eb-4af230f22eaf)

Test.ts:20 TypeError: (intermediate value)(intermediate value)(intermediate value) is not a constructor
    at Test.connect (Test.ts:18:27)
    at Test.start (Test.ts:13:14)
    at component-scheduler.ts:280:22
    at OneOffInvoker._invoke (component-scheduler.ts:247:13)
    at OneOffInvoker.invoke (component-scheduler.ts:162:14)
    at ComponentScheduler.startPhase (component-scheduler.ts:474:27)
    at Director.tick (director.ts:676:37)
    at Game._updateCallback (game.ts:1039:22)
    at Pacer.updateCallback [as _callback] (pacer-web.ts:95:22)
    at Pacer._handleRAF (pacer-web.ts:121:22)

**Comment by human211** [comment]
try
`import Colyseus from 'db://colyseus-sdk/colyseus.js';
...
this.client = new Colyseus.Client('http://localhost:2567');`

I dont know why but this works
