### ISSUE TITLE
Error trying to resolve module `httpie` from file (only on iOS)

### ISSUE THREAD

**Issue by virtumonde** [colyseus/colyseus.js#74]
Hi! The situation is the following: I am installing the colyseus.js client on my React Native app and it gives me the following error:
```
error: Error: While trying to resolve module `httpie` from file `/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/colyseus.js/lib/Client.js`, the package `/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/httpie/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/httpie/xhr/index.mjs`. Indeed, none of these files exist:

  * /Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/httpie/xhr/index.mjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/httpie/xhr/index.mjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/virtumonde/Desktop/dev/badlands/badlands-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
```

Everything Is alright on Android. The issue is present only on iOS.

**Comment by HishamMubarak** [comment]
Which of version Colyseus.js are you using? I had the same error in Android, but got it solved after using the following alpha release version.

> "colyseus.js": "^0.13.2-alpha.0",

**Comment by virtumonde** [comment]
@HishamMubarak Thank you for the reply! I will get back as soon as I test it.

**Comment by virtumonde** [comment]
@HishamMubarak thank you for helping me out. It works after updating.

**Comment by HishamMubarak** [comment]
> @HishamMubarak thank you for helping me out. It works after updating.

Glad to hear that. Don't forget to mark this issue as closed :)
