### ISSUE TITLE
Does it work in Node?

### ISSUE THREAD

**Issue by radiantone** [colyseus/colyseus.js#79]
When I try to run a simple client in nodejs it produces error

var client = new Colyseus.Client('ws://localhost:8002');
             ^
TypeError: Colyseus.Client is not a constructor
    at file:///xxxx/client.js:5:14
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:162:24)

**Comment by radiantone** [comment]
The answer is to add this

Colyseus = require('colyseus.js');

instead of 

import * as Colyseus from "colyseus.js"; // not necessary if included via <script> tag.
