### ISSUE TITLE
Error using Colyseus.js under vue.js + vite

### ISSUE THREAD

**Issue by slumtrimpet** [colyseus/colyseus.js#81]
After installing colyseus.js locally and trying to use it in a Typescript project built with 
[vite](https://v3.vuejs.org/guide/installation.html#vite) we get:

```
vite v1.0.0-rc.4
[vite] Optimizable dependencies detected:
colyseus.js, pixi.js, vue

[vite] Dep optimization failed with error:
Dependency @colyseus/http is attempting to import Node built-in module https.
This will not work in a browser environment.
Imported by: node_modules/@colyseus/http/dist/index.mjs

Tip:
Make sure your "dependencies" only include packages that you
intend to use in the browser. If it's a Node.js package, it
should be in "devDependencies".

If you do intend to use this dependency in the browser and the
dependency does not actually use these Node built-ins in the
browser, you can add the dependency (not the built-in) to the
"optimizeDeps.allowNodeBuiltins" option in vite.config.js.

If that results in a runtime error, then unfortunately the
package is not distributed in a web-friendly format. You should
open an issue in its repo, or look for a modern alternative.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Adding the following to vite.config.js:
``` 
  optimizeDeps: {
    allowNodeBuiltins: ['@colyseus/http' ]
  }
```

We then get:
```
  Error: ENOENT: no such file or directory, stat 'https'
      at Object.statSync (fs.js:855:3)
      at Object.statSync (/apps/consumer/node_modules/graceful-fs/polyfills.js:308:16)
      at cachedRead (/apps/consumer/node_modules/vite/dist/node/utils/fsUtils.js:24:45)
      at serve (/apps/consumer/node_modules/vite/dist/node/server/serverPluginModuleResolve.js:35:23)
      at app.use (/apps/consumer/node_modules/vite/dist/node/server/serverPluginModuleResolve.js:45:20)
      at dispatch (/apps/consumer/node_modules/koa-compose/index.js:42:32)
      at app.use (/apps/consumer/node_modules/vite/dist/node/server/serverPluginEnv.js:24:16)
      at dispatch (/apps/consumer/node_modules/koa-compose/index.js:42:32)
      at app.use (/apps/consumer/node_modules/vite/dist/node/server/serverPluginHtml.js:42:15)
      at dispatch (/apps/consumer/node_modules/koa-compose/index.js:42:32)
```

Is this anything that can be fixed or should we consider changing our compiler?

**Comment by endel** [comment]
Hi @slumtrimpet, I'm not familiar with vite, gonna try to reproduce this soon. Thanks for reporting!

**Comment by endel** [comment]
**Quick update:** I don't know how to specify different "browser" and "node" file versions of a package for ESM module loaders.

I've created some issues trying to get some answers, here:
- https://github.com/lukeed/httpie/issues/33
- https://github.com/vitejs/vite/issues/1154
